# GPU-specific configuration for TuSimple Lane Detection

defaults:
  - base_config

system:
  device: 'cuda'
  cuda_devices: [0]  # List of GPU indices to use
  pin_memory: true
  
training:
  batch_size: 16  # Increased batch size for GPU
  
optimization:
  memory_efficient: false
  cudnn_benchmark: true
  mixed_precision: true